// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
using System;

namespace Southwind.Models
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    /// <summary>
    /// Forwarding (Dummy) class
    /// Contains no functionality per se
    /// </summary>
    internal class IndexAttribute : Attribute
    {
        public IndexAttribute(string x, int y)
        {

        }
        public IndexAttribute(string x)
        {

        }
        public bool IsUnique { get; set; }
        public bool IsClustered { get; set; }
    }
}